version: "3.5"

volumes:
        wordpress:
                name: wordpress
                driver: local
                driver_opts:
                        device: /home/forstman/data/wordpress
                        o: bind
                        type: none
        mariadb:
                name: mariadb
                driver: local
                driver_opts:
                        device: /home/forstman/data/mariadb
                        o: bind
                        type: none

services:
  nginx:
    build: ./requirements/nginx/.
    ports:
     - "80:80"
    depends_on:
      - wordpress
    volumes:
     - wordpress:/var/www/html
    restart: always
  wordpress:
    build: ./requirements/wordpress/.
    depends_on:
      - mariadb
    volumes:
      - wordpress:/var/www/html
    restart: always
  mariadb:
    build: ./requirements/mariadb/.
    volumes:
      - mariadb:/var/lib/mysql
    restart: always