version: "3.5"

volumes:
        wordpress:
                name: wordpress
                driver: local
                driver_opts:
                        device: /Users/sahafid/Desktop/Inception/srcs/wordpress
                        o: bind
                        type: none
        mariadb:
                name: mariadb
                driver: local
                driver_opts:
                        device: /Users/sahafid/Desktop/Inception/srcs/mariadb
                        o: bind
                        type: none

services:
  nginx:
    build: ./requirements/nginx/.
    ports:
     - "443:443"
    depends_on:
      - wordpress
    volumes:
     - wordpress:/var/www/html
    restart: always
  wordpress:
    build: ./requirements/wordpress/.
    depends_on:
      - mariadb
    volumes:
      - wordpress:/var/www/html
    environment:
      - WP_DATABASE_NAME=wordpress
      - WP_DATABASE_USR=sami
      - WP_DATABASE_PWD=nice
      - WP_DATABASE_HOST=mariadb
      - DOMAIN_NAME=sahafid.1337.ma
      - WP_TITLE=RiadElYacoute
      - WP_ADMIN_USR=forstman1
      - WP_ADMIN_PWD=1231
      - WP_ADMIN_EMAIL=sami.hafid.hs@gmail.com
      - WP_USR=sami1
      - WP_EMAIL=sahafid@1337.com
      - WP_PWD=123
      - db_name=lol1
      - db_user=ss
      - db_pwd=tt
    restart: always
  mariadb:
    build: ./requirements/mariadb/.
    volumes:
      - mariadb:/var/lib/mysql
    environment:
      - db_name=lol1
      - db_user=ss
      - db_pwd=tt
    restart: always
  # ftp:
  #   build: ./requirements/bonus/ftp/.
  #   depends_on:
  #     - wordpress
  #   # volumes:
  #   #   - wordpress:/var/www/html
  #   ports:
  #     - "500:21"
  #   restart: always
  # adminer:
  #   build: ./requirements/bonus/adminer/.
  #   depends_on:
  #     - mariadb
  #   ports:
  #     - "600:80"
  #   restart: always
  # redis:
  #   build: ./requirements/bonus/redis/.
  #   volumes:
  #    - wordpress:/var/www/html
  #   depends_on:
  #     - wordpress
  #   restart: always
